name: Test Dump Files
on: push
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Dump Files
        run: |
          echo "=== package.json ==="
          cat package.json
          echo "=== eslint.config.js ==="
          cat eslint.config.js
